 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container gustavofbreunig-db-1  Creating
 Container gustavofbreunig-db-1  Created
 Container api_2  Creating
 Container api_1  Creating
 Container api_1  Created
 Container api_2  Created
 Container nginx  Creating
 Container nginx  Created
Attaching to api_1, api_2, db-1, nginx
db-1   | The files belonging to this database system will be owned by user "postgres".
db-1   | This user must also own the server process.
db-1   | 
db-1   | The database cluster will be initialized with locale "en_US.utf8".
db-1   | The default database encoding has accordingly been set to "UTF8".
db-1   | The default text search configuration will be set to "english".
db-1   | 
db-1   | Data page checksums are disabled.
db-1   | 
db-1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1   | creating subdirectories ... ok
db-1   | selecting dynamic shared memory implementation ... posix
db-1   | selecting default max_connections ... 100
db-1   | selecting default shared_buffers ... 128MB
db-1   | selecting default time zone ... Etc/UTC
db-1   | creating configuration files ... ok
db-1   | running bootstrap script ... ok
nginx  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1   | performing post-bootstrap initialization ... ok
db-1   | initdb: warning: enabling "trust" authentication for local connections
db-1   | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1   | syncing data to disk ... ok
db-1   | 
db-1   | 
db-1   | Success. You can now start the database server using:
db-1   | 
db-1   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1   | 
db-1   | waiting for server to start....2024-03-04 19:36:50.691 UTC [55] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1   | 2024-03-04 19:36:50.691 UTC [55] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1   | 2024-03-04 19:36:50.692 UTC [58] LOG:  database system was shut down at 2024-03-04 19:36:50 UTC
db-1   | 2024-03-04 19:36:50.695 UTC [55] LOG:  database system is ready to accept connections
db-1   |  done
db-1   | server started
db-1   | CREATE DATABASE
db-1   | 
db-1   | 
db-1   | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1   | SET
db-1   | SET
db-1   | SET
db-1   | SET
db-1   | SET
db-1   | SET
db-1   | SET
db-1   | SET
db-1   | SET
db-1   | SET
db-1   | SET
db-1   | CREATE TABLE
db-1   | CREATE TABLE
db-1   | DO
db-1   | 
db-1   | 
db-1   | 2024-03-04 19:36:50.952 UTC [55] LOG:  received fast shutdown request
db-1   | 2024-03-04 19:36:50.952 UTC [55] LOG:  aborting any active transactions
db-1   | waiting for server to shut down....2024-03-04 19:36:50.954 UTC [55] LOG:  background worker "logical replication launcher" (PID 61) exited with exit code 1
db-1   | 2024-03-04 19:36:51.015 UTC [56] LOG:  shutting down
db-1   | 2024-03-04 19:36:51.016 UTC [56] LOG:  checkpoint starting: shutdown immediate
db-1   | 2024-03-04 19:36:51.024 UTC [56] LOG:  checkpoint complete: wrote 939 buffers (7.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.001 s, total=0.008 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4288 kB, estimate=4288 kB; lsn=0/191AD38, redo lsn=0/191AD38
db-1   | 2024-03-04 19:36:51.033 UTC [55] LOG:  database system is shut down
db-1   |  done
db-1   | server stopped
db-1   | 
db-1   | PostgreSQL init process complete; ready for start up.
db-1   | 
db-1   | 2024-03-04 19:36:51.075 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1   | 2024-03-04 19:36:51.075 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1   | 2024-03-04 19:36:51.075 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1   | 2024-03-04 19:36:51.075 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1   | 2024-03-04 19:36:51.077 UTC [73] LOG:  database system was shut down at 2024-03-04 19:36:51 UTC
db-1   | 2024-03-04 19:36:51.080 UTC [1] LOG:  database system is ready to accept connections
nginx  | 2024/03/04 19:36:52 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.192.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:36:52 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.192.3:8080/clientes/1/extrato", host: "localhost:9999"
api_1  | 
api_1  |   .   ____          _            __ _ _
api_1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api_1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api_1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api_1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
api_1  |  =========|_|==============|___/=/_/_/_/
api_1  |  :: Spring Boot ::                (v3.2.2)
api_1  | 
api_2  | 
api_2  |   .   ____          _            __ _ _
api_2  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api_2  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api_2  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api_2  |   '  |____| .__|_| |_|_| |_\__, | / / / /
api_2  |  =========|_|==============|___/=/_/_/_/
api_2  |  :: Spring Boot ::                (v3.2.2)
api_2  | 
nginx  | 2024/03/04 19:36:54 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_1  | 2024-03-04T19:36:55.025Z  INFO 1 --- [           main] c.r.r.RinhadrivedesignApplication        : Starting RinhadrivedesignApplication v1.0.0 using Java 17.0.10 with PID 1 (/app.jar started by root in /)
api_1  | 2024-03-04T19:36:55.029Z  INFO 1 --- [           main] c.r.r.RinhadrivedesignApplication        : No active profile set, falling back to 1 default profile: "default"
api_2  | 2024-03-04T19:36:55.035Z  INFO 1 --- [           main] c.r.r.RinhadrivedesignApplication        : Starting RinhadrivedesignApplication v1.0.0 using Java 17.0.10 with PID 1 (/app.jar started by root in /)
api_2  | 2024-03-04T19:36:55.037Z  INFO 1 --- [           main] c.r.r.RinhadrivedesignApplication        : No active profile set, falling back to 1 default profile: "default"
nginx  | 2024/03/04 19:36:56 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:36:58 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:37:00 [error] 29#29: *7 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_1  | 2024-03-04T19:37:01.326Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
api_2  | 2024-03-04T19:37:01.636Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
api_1  | 2024-03-04T19:37:01.717Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 381 ms. Found 2 JPA repository interfaces.
api_2  | 2024-03-04T19:37:02.032Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 316 ms. Found 2 JPA repository interfaces.
nginx  | 2024/03/04 19:37:02 [error] 29#29: *8 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:37:04 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.192.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:37:04 [error] 29#29: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.192.4:8080/clientes/1/extrato", host: "localhost:9999"
api_1  | 2024-03-04T19:37:06.524Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
api_1  | 2024-03-04T19:37:06.620Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
api_1  | 2024-03-04T19:37:06.621Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
api_2  | 2024-03-04T19:37:06.721Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
api_2  | 2024-03-04T19:37:06.821Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
api_2  | 2024-03-04T19:37:06.821Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
nginx  | 2024/03/04 19:37:06 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_1  | 2024-03-04T19:37:07.322Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
api_1  | 2024-03-04T19:37:07.324Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 11901 ms
api_2  | 2024-03-04T19:37:07.439Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
api_2  | 2024-03-04T19:37:07.440Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 12007 ms
nginx  | 2024/03/04 19:37:08 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_1  | 2024-03-04T19:37:10.224Z  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
api_2  | 2024-03-04T19:37:10.519Z  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
api_1  | 2024-03-04T19:37:10.533Z  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.4.1.Final
api_1  | 2024-03-04T19:37:10.732Z  INFO 1 --- [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
api_2  | 2024-03-04T19:37:10.837Z  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.4.1.Final
nginx  | 2024/03/04 19:37:11 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_2  | 2024-03-04T19:37:11.031Z  INFO 1 --- [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
api_1  | 2024-03-04T19:37:12.235Z  INFO 1 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
api_1  | 2024-03-04T19:37:12.338Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
api_2  | 2024-03-04T19:37:12.425Z  INFO 1 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
api_2  | 2024-03-04T19:37:12.542Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
nginx  | 2024/03/04 19:37:13 [error] 29#29: *15 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api_1  | 2024-03-04T19:37:13.434Z  INFO 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@361f26b4
api_1  | 2024-03-04T19:37:13.436Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
api_2 exited with code 137
api_1 exited with code 137
nginx  | 2024/03/04 19:37:49 [error] 29#29: *16 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.192.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:08 [error] 29#29: *16 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.192.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:13 [error] 29#29: *19 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.192.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:13 [error] 29#29: *19 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:15 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:17 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:22 [error] 29#29: *23 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.192.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:22 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:27 [error] 29#29: *25 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.192.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:27 [error] 29#29: *25 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:29 [error] 29#29: *27 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:31 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:36 [error] 29#29: *29 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.192.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx  | 2024/03/04 19:38:36 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 192.168.192.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx exited with code 0
nginx exited with code 0
db-1   | 2024-03-04 19:38:39.145 UTC [1] LOG:  received fast shutdown request
db-1   | 2024-03-04 19:38:39.145 UTC [1] LOG:  aborting any active transactions
db-1   | 2024-03-04 19:38:39.147 UTC [1] LOG:  background worker "logical replication launcher" (PID 76) exited with exit code 1
db-1   | 2024-03-04 19:38:39.147 UTC [71] LOG:  shutting down
db-1   | 2024-03-04 19:38:39.147 UTC [71] LOG:  checkpoint starting: shutdown immediate
db-1   | 2024-03-04 19:38:39.148 UTC [71] LOG:  checkpoint complete: wrote 46 buffers (0.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.001 s; sync files=0, longest=0.000 s, average=0.000 s; distance=99 kB, estimate=99 kB; lsn=0/1933C50, redo lsn=0/1933C50
db-1   | 2024-03-04 19:38:39.152 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
